#if canImport(CloudKit)
import CloudKit
import CloudKitProvisioning
import Foundation
import HouseholdRecords
import HouseholdSync
import OSLog
import SimmerSmithKit
import SwiftData

// SP-C slice 5 — one-time Fly→CloudKit migration of:
//
//   • /api/pantry               → .pantryItem records (household zone)
//   • /api/household (aliases)  → .householdTermAlias records (household zone, det-key)
//   • /api/profile              → PrivateProfileSetting (NON-AI keys, private plane)
//                                  + PrivateDietaryGoal (private plane)
//   • /api/ingredient-preferences → PrivateIngredientPreference (private plane)
//   • Preference signals        → NOT migrated — they are generated by the AI assistant
//                                  at runtime (no Fly endpoint exists for them).
//
// RECEIPT: scope "pantry-profile" — a PRIVATE-plane receipt via
// `PrivatePlaneStore.claimMigrationScope("pantry-profile")`. The private plane auto-syncs
// to all the user's devices (NSPCKC), so once this device stamps the receipt the other
// devices skip the migration next time they boot. (Contrast the household receipts used by
// weeks/events, which live in the CKSyncEngine zone and sync the same way but via a
// different mechanism.) We use the private-plane receipt here because pantry+aliases write
// to the HOUSEHOLD zone while profile/prefs write to the PRIVATE plane, and there is no
// single plane that owns both. The private-plane receipt was chosen over a household zone
// receipt because (a) profile/prefs are fundamentally per-user data, and (b) the private
// store is guaranteed to be available whenever the private-plane repos are in use.
//
// WRITE ORDER (crash-safe):
//   (1) .pantryItem records → household engine
//   (2) .householdTermAlias records → household engine
//   (3) PrivateProfileSetting + PrivateDietaryGoal → private plane store.save()
//   (4) PrivateIngredientPreference → private plane store.save()
//   (5) private plane receipt (claimMigrationScope) + store.save()   ← LAST
//   (6) household engine.sendUntilDrained()
// A crash anywhere before step (5) leaves no receipt, so the retry re-runs. The engine's
// PK-preserving upserts and the private plane's fetch-before-insert upserts make every
// step idempotent.
//
// ONE-SHOT FLY AUTH: same pattern as WeekMigrationLoader / EventMigrationLoader. The
// caller (AppState.importPantryProfileFromFly) is responsible for exchanging the Apple
// identity token for a Fly JWT and setting it on the apiClient before calling this
// function. The token is cleared by the caller after migration.
//
// NON-AI PROFILE KEYS ONLY: image_provider / unit_system / user_region /
// auto_grocery_from_meals. The AI provider config + API key → Keychain (AI track). The
// `ProfileRepository.nonAIKeys` constant is the authoritative list.

private let pantryProfileMigrationScope = "pantry-profile"
private let log = Logger(subsystem: "app.simmersmith.cloud", category: "PantryProfileMigrationLoader")

/// True when no private-plane upsert was dropped during the migration write phase — the
/// completeness check the RECEIPT-BLOCKING RULE (in `migratePantryProfileIfNeeded` below)
/// gates the receipt stamp on. Internal (not private) so the app-target test can pin the
/// contract.
func pantryProfileMigrationIsComplete(droppedCount: Int) -> Bool {
    droppedCount == 0
}

// MARK: - Migration entry point

/// Pull pantry items, household aliases, and per-user profile/preferences from Fly and
/// write them into the household CloudKit zone (pantry + aliases) and the private plane
/// (profile settings, dietary goal, ingredient preferences). No-op if the
/// "pantry-profile" receipt is already present in the private plane. The caller is
/// responsible for ensuring the apiClient's auth token is set before calling this.
///
/// - Parameters:
///   - session: the live CloudKit household session (zone provisioned + first fetch done).
///   - apiClient: the Fly API client with a valid auth token already set.
@MainActor
func migratePantryProfileIfNeeded(
    session: HouseholdSession,
    apiClient: SimmerSmithAPIClient
) async {
    // Gate: skip if the private-plane receipt is already present. A nil privateStore means
    // the private plane didn't boot (iCloud unavailable or container creation failed) —
    // leave the receipt unstamped so the next launch with a working private plane retries.
    guard let privateStore = session.privateStore else { return }

    let alreadyMigrated: Bool
    do {
        alreadyMigrated = try privateStore.fetchFirst(
            #Predicate<PrivateMigrationReceipt> { $0.recordKey == pantryProfileMigrationScope }
        ) != nil
    } catch {
        // Can't read receipts — skip safely; retry on next launch.
        return
    }
    guard !alreadyMigrated else { return }

    // ── 1. Fetch pantry items ────────────────────────────────────────────────

    let pantryItems: [PantryItem]
    do {
        pantryItems = try await apiClient.fetchPantryItems()
    } catch {
        // Network unavailable or Fly token invalid — leave receipt unstamped for retry.
        return
    }

    // ── 2. Fetch household aliases ───────────────────────────────────────────

    let aliases: [HouseholdTermAlias]
    do {
        aliases = try await apiClient.fetchHouseholdAliases()
    } catch {
        aliases = []  // not fatal; pantry + profile still migrate
    }

    // ── 3. Fetch profile (non-AI settings + dietary goal) ───────────────────

    let flyProfile: ProfileSnapshot?
    do {
        flyProfile = try await apiClient.fetchProfile()
    } catch {
        flyProfile = nil  // not fatal
    }

    // ── 4. Fetch ingredient preferences ──────────────────────────────────────

    let ingredientPreferences: [IngredientPreference]
    do {
        ingredientPreferences = try await apiClient.fetchIngredientPreferences()
    } catch {
        ingredientPreferences = []  // not fatal
    }

    // ── Write phase ──────────────────────────────────────────────────────────

    // (1) .pantryItem records → household engine. PantryItem.pantryItemId is the stable
    // UUID pk (namePolicy .pk), so the record name is the id as-is. Serialise categories
    // as JSON-array string (matches PantryRepository.serializeCategories).
    for item in pantryItems {
        let categoriesSerialized: String
        if let data = try? JSONSerialization.data(withJSONObject: item.categories),
           let str = String(data: data, encoding: .utf8) {
            categoriesSerialized = str
        } else {
            categoriesSerialized = "[]"
        }

        var scalars: [String: ScalarValue] = [
            "stapleName":       .string(item.stapleName),
            "normalizedName":   .string(item.normalizedName),
            "notes":            .string(item.notes),
            "isActive":         .bool(item.isActive),
            "typicalUnit":      .string(item.typicalUnit),
            "recurringUnit":    .string(item.recurringUnit),
            "recurringCadence": .string(item.recurringCadence),
            "category":         .string(item.category),
            "categories":       .string(categoriesSerialized),
            "createdAt":        .date(item.updatedAt),
            "updatedAt":        .date(item.updatedAt),
        ]
        if let q = item.typicalQuantity   { scalars["typicalQuantity"]   = .double(q) }
        if let q = item.recurringQuantity { scalars["recurringQuantity"] = .double(q) }
        if let d = item.lastAppliedAt     { scalars["lastAppliedAt"]     = .date(d) }
        if let d = item.frozenAt          { scalars["frozenAt"]           = .date(d) }

        let value = HouseholdRecordValue(
            type: .pantryItem,
            recordName: item.pantryItemId,
            scalars: scalars,
            refs: [:]
        )
        session.engine.save(HouseholdRecordCodec.encode(value, zoneID: session.zoneID))
    }

    // (2) .householdTermAlias records → household engine (det-keyed by term).
    // AliasRepository.upsertAlias uses RecordNames.termAlias(term:) for the recordName.
    let now = Date()
    for alias in aliases {
        let recordName = RecordNames.termAlias(term: alias.term)
        let value = HouseholdRecordValue(
            type: .householdTermAlias,
            recordName: recordName,
            scalars: [
                "term":      .string(alias.term),
                "expansion": .string(alias.expansion),
                "notes":     .string(alias.notes),
                "createdAt": .date(alias.updatedAt),
                "updatedAt": .date(alias.updatedAt),
            ],
            refs: [:]
        )
        session.engine.save(HouseholdRecordCodec.encode(value, zoneID: session.zoneID))
    }

    // (3) Profile settings + dietary goal → private plane.
    // NON-AI keys only (ProfileRepository.nonAIKeys). Skip nil flyProfile gracefully.
    // RECEIPT-BLOCKING RULE (mirrors RecipeMigrationLoader): count attempted vs
    // succeeded per-item upserts in (3) and (4); any drop withholds the receipt below
    // so the next launch retries (idempotent — every upsert here is fetch-by-key).
    // Household writes in (1)/(2) use non-throwing engine.save and are not part of
    // this count.
    var attemptedPrivateUpserts = 0
    var droppedPrivateUpserts = 0
    if let profile = flyProfile {
        let nonAIKeys = ProfileRepository.nonAIKeys
        for key in nonAIKeys {
            if let value = profile.settings[key] {
                attemptedPrivateUpserts += 1
                do {
                    try privateStore.upsertProfileSetting(key: key, value: value, updatedAt: profile.updatedAt ?? now)
                } catch {
                    droppedPrivateUpserts += 1
                }
            }
        }
        if let goal = profile.dietaryGoal {
            attemptedPrivateUpserts += 1
            do {
                try privateStore.upsertDietaryGoal(
                    goalType: goal.goalType.rawValue,
                    dailyCalories: goal.dailyCalories,
                    proteinG: goal.proteinG,
                    carbsG: goal.carbsG,
                    fatG: goal.fatG,
                    fiberG: goal.fiberG ?? 0,
                    notes: goal.notes,
                    updatedAt: goal.updatedAt ?? now
                )
            } catch {
                droppedPrivateUpserts += 1
            }
        }
        try? privateStore.save()
    }

    // (4) Ingredient preferences → private plane (id-keyed on preferenceId).
    // Pass baseIngredientName from the Fly response so the allergy hard-gate has a name
    // to match against without a catalog round-trip (C1 fix).
    for pref in ingredientPreferences {
        attemptedPrivateUpserts += 1
        do {
            try privateStore.upsertIngredientPreference(
                preferenceID: pref.preferenceId,
                baseIngredientID: pref.baseIngredientId,
                baseIngredientName: pref.baseIngredientName,
                choiceMode: pref.choiceMode,
                rank: pref.rank,
                active: pref.active,
                brand: pref.preferredBrand,
                variation: pref.preferredVariationId ?? "",
                updatedAt: pref.updatedAt
            )
        } catch {
            droppedPrivateUpserts += 1
        }
    }
    if !ingredientPreferences.isEmpty {
        try? privateStore.save()
    }

    // (5) Drain household writes to CloudKit BEFORE the receipt is stamped. The engine's
    // automaticSync also fires in the background, but an explicit drain ensures the
    // household records (pantry + aliases) reach the server before we mark the migration
    // done. A crash between the household save and the receipt stamp leaves NO receipt, so
    // the next launch retries the whole migration (idempotent via the engine's
    // PK-preserving upserts and the private plane's fetch-before-insert upserts).
    try? await session.engine.sendUntilDrained()

    // RECEIPT-BLOCKING RULE: any dropped profile-setting / dietary-goal / ingredient-
    // preference upsert withholds the receipt so the next launch retries the whole
    // migration (idempotent — every private-plane upsert above is fetch-by-key).
    guard pantryProfileMigrationIsComplete(droppedCount: droppedPrivateUpserts) else {
        log.error("pantry-profile migration dropped \(droppedPrivateUpserts, privacy: .public) of \(attemptedPrivateUpserts, privacy: .public) private-plane upserts; receipt withheld for retry")
        return
    }

    // (6) Stamp the private-plane receipt LAST — crash-safety invariant (matches
    // WeekMigrationLoader). The receipt must be the final write so a crash before it
    // leaves the migration un-done and the retry re-runs from the top.
    guard (try? privateStore.claimMigrationScope(pantryProfileMigrationScope, at: now)) != nil else { return }
    try? privateStore.save()
}

// MARK: - Private helper extension (fetch migration receipt from private plane)

private extension PrivatePlaneStore {
    /// Fetch the first model matching the predicate. Mirrors PrivatePlaneStore's own private helper —
    /// we need it here because the method is private to the struct.
    func fetchFirst<T: PersistentModel>(_ predicate: Predicate<T>) throws -> T? {
        var descriptor = FetchDescriptor<T>(predicate: predicate)
        descriptor.fetchLimit = 1
        return try context.fetch(descriptor).first
    }
}
#endif
